version: '3'
services:
  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    ports:
      - "19120:19120"
    depends_on:
      - mongo
    environment:
      - nessie.version.store.type=MONGODB
      - quarkus.mongodb.database=nessie
      - quarkus.mongodb.connection-string=mongodb://root:password@mongo:27017
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/cloud_user/mongodb:/data/db:rw

  minioserver:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    container_name: minio
    volumes:
     - /home/cloud_user/minio:/data:rw
    command: server /data --console-address ":9001"
